version: "3"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"

  mongodb:
    image: mongo:4.4.6
